# Configurações gerais do Spring Boot
spring:
  # Nome da aplicação
  application:
    name: rest-with-sprong-boot-and-java-luke
  
  # Configurações do banco de dados
  datasource:
    # Driver JDBC para MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    # URL de conexão com o banco de dados
    # useTimezone: ajusta o fuso horário do cliente
    # serverTimezone=UTC: define o fuso horário do servidor como UTC
    url: jdbc:mysql://localhost:3306/rest_with_sprong_boot_luke?useTimezone=true&serverTimezone=UTC
    # Credenciais do banco de dados
    username: root
    password: 314152
  
  # Configurações do JPA (Java Persistence API)
  jpa:
    hibernate:
      # Estratégia de atualização do banco de dados
      # update: atualiza o esquema do banco de dados se necessário
      ddl-auto: update
    # Configurações específicas do Hibernate
    properties:
      hibernate:
        # Dialeto SQL específico para MySQL 8
        # Otimiza as consultas para o MySQL 8
        dialect: org.hibernate.dialect.MySQL8Dialect
    # Mostrar as consultas SQL no console (útil para depuração)
    show-sql: false